# Generated by Django 5.0.4 on 2024-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('popular', models.BooleanField(default=False)),
                ('blog_date', models.DateTimeField()),
            ],
        ),
    ]
